{{- $root := . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scouter.fullname" . }}
  labels:
    {{- include "scouter.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- tpl (toYaml . | nindent 4) $root }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "scouter.selectorLabels" . | nindent 4 }}
