apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            Endpoint:  0.0.0.0:4317
          http:
            Endpoint:  0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
            job_name: otel-collector
            scrape_interval: 10s
            static_configs:
              targets:
                0.0.0.0:8888

    processors:
      batch:
        send_batch_size:  10000
        timeout:          10s
      memory_limiter:
        check_interval:          1s
        limit_percentage:        75
        spike_limit_percentage:  15

    exporters:
      otlp:
        endpoint:  tempo-tempo:4317
        tls:
          Insecure:  true
      prometheusremotewrite:
        endpoint:  http://prometheus-server/api/v1/write
        external_labels:
          Source:  otelcol

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp, prometheus]
          processors: [memory_limiter,batch]
          exporters: [prometheusremotewrite]